### PR TITLE
Fix wallet crash when the wallet initiates reindex

### LINKED ISSUE #779: Wallet crashes when blockchain DB load fails
## Actual behaviour
If blockchain DB load error occures, the wallet crashes, and reindexing is initiated by the wallet.

### PR DESCRIPTION
**Pull request by a-bezrukov**
Fixes #779

### CODE REVIEW

File: src/init.cpp [hunk 1]
```diff
@@ -1668,6 +1668,7 @@ bool AppInit2(boost::thread_group &threadGroup, CScheduler &scheduler) {
                 delete pcoinsdbview;
                 delete pcoinscatcher;
                 delete pblocktree;
+                sigma::CSigmaState::GetState()->Reset();
```
Comment (levonpetrosyan93) [inline src/init.cpp]: Wold it be more logical to move this to UnloadBlockIndex() function?

Comment (a-bezrukov) [reply src/init.cpp]: There is no logical evidence that moving this into UnloadBlockIndex will make the program any better as UnloadBlockIndex is called exactly once 4 lines above. 
It maybe more aesthetic to put it there. That's why I am doing so.

Comment (levonpetrosyan93) [reply src/init.cpp]: Saying logical, I mean all such calls are at UnloadBlockIndex.
